joints:
  name:
    - right_arm_0_joint
    - right_arm_1_joint
    - right_arm_2_joint
    - right_arm_3_joint
    - right_arm_4_joint
    - right_arm_5_joint
    - right_arm_6_joint
    - left_arm_0_joint
    - left_arm_1_joint
    - left_arm_2_joint
    - left_arm_3_joint
    - left_arm_4_joint
    - left_arm_5_joint
    - left_arm_6_joint
    - triangle_base_joint
    - neck_shoulder_pan_joint
    - neck_shoulder_lift_joint
    - neck_elbow_joint
    - neck_wrist_1_joint
    - neck_wrist_2_joint
    - neck_wrist_3_joint
  position:
    - -0.31
    - -1.43
    - 1.16
    - 1.52
    - -1.16
    - -1.17
    - 0.1
    - 0.36
    - 1.41
    - 1.96
    - 1.52
    - -2.1
    - 0.9
    - 0.1
    - -0.4
    - 1.6133809977777778
    - -1.1410953011111111
    - 1.635197595
    - -1.4261073272222222
    - 1.5552615827777778
    - 3.0162754655555553
